### ISSUE TITLE
[enhancement] Kanji search with SKIP method

### ISSUE THREAD

**Issue by nicolas-raoul** [odrevet/gjitenkai#2]
It would be great if one could search for a kanji using the SKIP method :-)

http://kanji.sljfaq.org/skip.html
http://softwarerecs.stackexchange.com/questions/21209

**Comment by odrevet** [comment]
This is impossible as SKIP code copyright is not compatible with EDICT or
GPL and has been striped from KANJIDIC

2015-07-17 12:12 GMT+02:00 Nicolas Raoul <notifications@github.com>:

**Comment by nicolas-raoul** [comment]
SKIP was stripped from KANJIDIC in 1993.
But in December 2014, usage became much more permissive, with a [Creative Commons Attribution-ShareAlike 4.0 International ](http://creativecommons.org/licenses/by-sa/4.0/) license: http://www.kanji.org/kanji/dictionaries/skip_permission.htm

Bundling the SKIP database inside GPL software is still not doable, but the software could download it at first use.
Cheers!

**Comment by odrevet** [comment]
I did not know that. I see that monash's kanjidic (warning, heavy file in
diretc link http://ftp.monash.edu.au/pub/nihongo/kanjidic.gz) re-putted
SKIP code. So it may be an option for a future feature

2015-07-17 12:25 GMT+02:00 Nicolas Raoul <notifications@github.com>:

**Comment by odrevet** [comment]
I think the new license is compatible GPL as it is now usable "for any
purpose, even commercially."which was the reason it was removed in the
first place

2015-07-17 12:45 GMT+02:00 Olivier Drevet <odrevet@gmail.com>:

**Comment by nicolas-raoul** [comment]
The current license still requires attribution, which is incompatible with GNU-GPL.

**Comment by odrevet** [comment]
I cannot implement something not GPL, even if I wanned to which is not the case. 
But the good news is you can still search for  skip code in every version of gjiten (2.6 included) with the search by key field. It's not documented, but it search in kdicfile for plein text. You need a version of kanjidic (kdicfile) not stripped of it's SKIP keys, and in search by key filter enter P followed by your skip code. 
I am closing this issu for now, until further info on this licensing problem.
