### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by tatsuhirosatou** [odrevet/gjitenkai#4]
https://launchpad.net/~odrevet/+archive/ubuntu/gjiten-kai

Thanks for your project!

I found this page. Is there any hope of an Ubuntu PPA for gjitenkai?

**Comment by odrevet** [comment]
Hi, 
I tried but I could not figure out how to build directly from github.

**Comment by odrevet** [comment]
The PPA archives are build and online. 
Could not see any update after adding the repo (maybe because the servers need time to apply changes)
This Issu will be closed when installation from this ppa can be confirmed possible

**Comment by tatsuhirosatou** [comment]
```
E: The repository 'http://ppa.launchpad.net/odrevet/gjiten-kai/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

I am getting this error when I try to install from the PPA

**Comment by odrevet** [comment]
Hi, 
this is a release for yakkety. 
You should upgrade your Ubuntu to the current latest version

**Comment by tatsuhirosatou** [comment]
I see, thanks!

2017年1月24日(火) 2:59 DREVET Olivier <notifications@github.com>:
