### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by baimafeima** [odrevet/gjitenkai#5]
Please advise whether this project is still maintained. Any plans to have versioned tarball releases here on GitHub?

**Comment by odrevet** [comment]
This project is not abandoned, 
For the moment I like it the way it is so I do not make any modifications, but I will fix any bugs or maybe in the future make new feature is I need them (or merge a feature that looks interesting)

**Comment by baimafeima** [comment]
> Versioned Release on github is a good idea, I will certainly lookup how this works soon.

Thanks for the quick reply and I am glad to see that your project is still alive. There are not many good and actively maintained dictionaries around, especially for Linux-based operating systems. I am looking forward to a new versioned tarball release.

**Comment by odrevet** [comment]
Version 0.1 Released

**Comment by baimafeima** [comment]
@odrevet Thank you for your quick response. I just want to inform you that Gjitenkai was recently added to the Solus repositories: https://git.solus-project.com/packages/gjitenkai/commit/?id=618c4c1c0bdb568432e8aed1fe14638a4ac216c5

**Comment by odrevet** [comment]
great !
