### ISSUE TITLE
Fetch EDICT dictionary files via GUI

### ISSUE THREAD

**Issue by baimafeima** [odrevet/gjitenkai#6]
This is a feature request to increase the OOTB experience when using gjitenkai. Could you implement a graphical solution to fetching the EDICT dictionary files via the regular interface instead of prompting a new user to download it manually? I know this is a lot of work but it would make it so much more usable. Are you familiar with the Chinese Android-based pleco dictionary? I am not sure to what extent this is comparable but they have made such a function available as part of their interface.

**Comment by odrevet** [comment]
This is a possibility, however I can't make it in the near futur.

**Comment by odrevet** [comment]
The requested functionality has been added. 
A download button located in the welcome box and in the help menu download the gz unicode version of edict from monash ftp and add the file as an activated dictionary if download succeed. 
This is a simple but working stub that may be expanded in the futur (list of available dictionary in a file or gsettings, update, etc...)

**Comment by baimafeima** [comment]
Awesome, thanks a lot. Whenever your next tagged release is out, I will suggest it to be updated in the repos and then test it.

**Comment by odrevet** [comment]
I also have changed a lot of things beside that. 
I need to test the windows build which is probably brocken and add a Japanese translation, after that I will make a release next week.
