### ISSUE TITLE
Japanese fonts

### ISSUE THREAD

**Issue by baimafeima** [odrevet/gjitenkai#7]
What are currently the best open source fonts that you would recommend to be used alongside gjitenkai?

**Comment by odrevet** [comment]
I am using "Sans regular"  for the eddict part and "monospace regular" for the kanjidic part. 
I also recommand "Kanji Stroke Order" for the kanji display

**Comment by baimafeima** [comment]
Thanks, do you have any links to the upstream font projects?

**Comment by odrevet** [comment]
Here is the page for kanji stroke order http://kanji.sljfaq.org/kanjivg.html
I don't have upstream pages for the other fonts
