### ISSUE TITLE
After maximizing the window control buttons disappear

### ISSUE THREAD

**Issue by baimafeima** [odrevet/gjitenkai#9]
After maximizing the application window, the window control buttons (minimize, maximize, close) disappear.

**Comment by odrevet** [comment]
this is must have something to do with the option  
```
<property name="hide_titlebar_when_maximized">True</property> of 
```

https://github.com/odrevet/gjitenkai/blob/master/share/gjitenkai/ui/gjitenkai.ui#L89

I remember to have set this option as a personal preference but I can understand how the normal dehaviour should be used

**Comment by baimafeima** [comment]
I see. I can understand that you probably wanted to save screen space. Would you consider reverting this and perhaps make it available via an optional toolbox in the preferences?

**Comment by odrevet** [comment]
fixed and tested
